project:
  type: website
  output-dir: docs

website:
  title: "Zoey Yandell"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: education.qmd
        text: Education
      - href: experience.qmd
        text: Experience
      - href: projects.qmd
        text: Projects
      
page-footer:
  left: |
    &copy; Zoey Yandell, 2023<br>
    All content licensed under <i class='bi-badge-cc'></i>
    [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
  right: |
    Site built with <a href='https://quarto.org/'>Quarto</a>


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

