---
title: "Education and Skills"
---

## Macalester College

St. Paul, MN

B.A. in Mathematics and Environmental Studies (Urban Sustainability) \| Sept 2020 - May 2024

Relevant Coursework: - \[copypaste\]

Capstone: Analyzing bias in transportation systems using agent-based modeling \[link to project page\]

## DIS Study Abroad in Copenhagen

Copenhagen, DK

August - December 2022

\[check master resume overview\]

Relevant Coursework: - Sustainable Development in Northern Europe - Geographic Information Systems: Applied Climate Change Cases - Principles of Urban Livability - Sustainable by Design

## SDSN Youth Local Pathways Fellowship

March 2024 - March 2025

\[copy from website\]

## Skills

-   proficient in R and RStudio

    -   used for data visualization and app development

    -   package proficiencies include tidyverse, shiny, quarto, sf, ggplot2 and plotly

    -   see projects: \[212 project\] \[strategy planning tool\] \[ghg inventory\] \[155 projects\]

-   intermediate understanding of Python

    -   used for mathematical modeling, data visualization and varied programming tasks

    -   see projects: \[math capstone\] \[123 project\] \[alliaria\]

-   intermediate understanding of MATLAB

    -   used for mathematical modeling

    -   see projects: \[alliaria\]

-   basic understanding of C++

    -   used for mathematical modeling

    -   see projects: \[alliaria\]

-   intermediate understanding of ArcGIS Pro

-   intermediate understanding of Excel
