---
title: "Experience"
---

<!--# try two columns -->

::: {#intro-heading}
## Experience

I am a upcoming graduate of Macalester College with a degree in Environmental Studies and Mathematics, concentrating in Urban Sustainability. Currently, I work as a Climate Data Analyst at the Metropolitan Council of the Twin Cities, putting my multidisciplinary background to work developing data tools and environmental policy for the metropolitan region. I also channel my passion for the environment into activism with Sunrise Twin Cities, where I serve as a democratic representative to the national Sunrise movement and contribute as a lead researcher and writer to youth-led climate activism with national scale and local focus.

Recently, I was named as a SDSN Youth Local Pathways Fellow, joining a global group of young urban sustainability professionals in an internationally-recognized program to advance SDG 11 and build the global youth sustainability movement.
:::

## Metropolitan Council

## Sunrise Twin Cities

## Research at Macalester College
